### ISSUE TITLE
Compile failure with base < 4.6

### ISSUE THREAD

**Issue by hvr** [Happstack/web-routes#5]
e.g.

```
Configuring component lib from web-routes-0.27.12...
Preprocessing library web-routes-0.27.12...
[1 of 6] Compiling Web.Routes.RouteT ( Web/Routes/RouteT.hs, /tmp/matrix-worker/1499092109/dist-newstyle/build/x86_64-linux/ghc-7.4.2/web-routes-0.27.12/build/Web/Routes/RouteT.o )

Web/Routes/RouteT.hs:41:26:
    Ambiguous occurrence `catch'
    It could refer to either `Prelude.catch',
                             imported from `Prelude' at Web/Routes/RouteT.hs:14:8-24
                             (and originally defined in `System.IO.Error')
                          or `Control.Monad.Catch.catch',
                             imported from `Control.Monad.Catch' at Web/Routes/RouteT.hs:18:29-45

```

We have already revised the affected releases 

- https://hackage.haskell.org/package/web-routes-0.27.9/revisions
- https://hackage.haskell.org/package/web-routes-0.27.10/revisions
- https://hackage.haskell.org/package/web-routes-0.27.11/revisions
- https://hackage.haskell.org/package/web-routes-0.27.12/revisions
- https://hackage.haskell.org/package/web-routes-0.27.13/revisions
- https://hackage.haskell.org/package/web-routes-0.27.14/revisions

See  also https://matrix.hackage.haskell.org/package/web-routes for an overall overview

**Comment by stepcut** [comment]
Thanks. The oldest compiler we now support is GHC 8.0.2 and we now have base >= 4.9.
